import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
from heapq import nlargest
from scrapers import abc_scraper, guardian_scraper, ctv_scraper, nbc_scraper


# GOTTA CHANGE ALL TEXT TO LOWER AND STRIP PUNCTUATION

# build a list of stopwords
stopwords = list(STOP_WORDS)

# nlp.Defaults.stop_words.add("my_new_stopword") # Replace my_new_stopword with a custom stopword

document1 = """Strategic Alliance Committee (SAC) between Jaztec Inc. and FCC Foundations was created to develop web-based marketing and promotional activities to strengthen relationships between the two companies through exposing Jaztec’s clientele to FCC Foundations’ services and vice versa. Team members signed a committee covenant and agreed to work cooperatively under Jovianna in order to develop and execute a plan which would mutually benefit both organizations. These are the individuals involved in the SAC:
•	Jovianna Gucci – Team Leader, VP Marketing and PR, Jaztec Inc.
•	Miguel Cameron – Web Designer, Jaztec Inc.
•	Rachelle Ricardo – Executive Director of Communications and Marketing, FCC Foundations
•	Kareena Gonsalves – Executive Director of Logistics and Planning, FCC Foundations
•	Tate Andrews – Director, 2002-2003 Board of Directors, FCC Foundations
Miguel is talented but shows a lack of commitment to the project by consistently being late or absent from team meetings and has boarded a flight to Spain without notifying Jovianna or getting her approval. Tate has grown demotivated due to Miguel’s lack of performance. Although she sympathizes with Miguel’s personal situation, he wants Miguel to be held accountable for his actions and told that his behaviour is unacceptable. Rachelle and Kareena openly opposed and resisted Jovianna’s leadership right from the first meeting. They hinder the SAC’s ability to cooperate and make it difficult for Jovianna to lead the group by discouraging her with negative body language, facial expressions, and an aggressive tone during meetings. Jovianna reacted poorly in response to criticism from Rachelle and Kareena and resorted to bringing her manager Jerome into a SAC meeting in an attempt to solidify her position as the leader. This failed to change Rachelle and Kareena’s attitude and caused resentment instead. In a private meeting between Jovianna, Rachelle, and Kareena, Rachelle and Kareena presented suggestions on how Jovianna could improve as a leader, but Jovianna lost her temper and screamed at the two FCC employees. The SAC’s ongoing intergroup conflict has cumulated in Rachelle and Kareena asking for Jovianna’s resignation from the Team Leader position and threatening to remove FCC Foundations from the alliance.
SAC roles should be re-established while exploring the possibility of co-leadership. A cooperative leadership position will ensure both organizations are equally represented. Miguel should be reprimanded for his lack of professionalism and given a choice to commit to the project or voluntarily leave. Jovianna should issue a formal apology for her lack of professionalism and take appropriate steps to understand the other team members in order to prevent future outbursts. The SAC will benefit from increased communication and full disclosure of any dissatisfaction between team members.
We can use the five types of individual behaviours outlined in McShane and Tasa’s Canadian Organizational Behaviour to identify problems within the SAC. This section identifies symptoms of individual behaviours displayed by members of the SAC.
Organizational citizenship is defined as discretionary employee behaviours which go beyond regular workplace duties but support the organization’s social and psychological context. Jovianna starts off with a strong commitment to SAC and making the alliance work, emphasizing how a successful coalition between the two companies would benefit her personal career. Miguel shows a lack of commitment to the SAC by occasionally failing to show up for meetings and often arriving late. Rachelle and Kareena exhibit strong organizational citizenship towards FCC Foundations but not towards SAC, which is demonstrated when Rachelle outright states that the FCC members are not at the meeting to brainstorm for Jaztec’s advancement.
Voluntary actions or activities which potentially harm the organization both directly and indirectly can be described as counterproductive work behaviours. Most members of the SAC exhibit counterproductive work behaviours. Rachelle and Kareena’s display of hostility and disrespect to Jovianna creates a toxic environment during team meetings. Miguel avoids questions about the website’s progress and only produces templates when he feels the need to. Jovianna reacts negatively and aggressively to Rachelle and Kareena’s attempt to approach her with suggestions on how to improve her leadership.
Attendance describes whether or not an individual shows up on time to work. Miguel struggles with attending meetings on time and occasionally misses entire meetings without notice. Rachelle makes it difficult for Jovianna to schedule future meetings by making bold statements about how she was too busy to meet on a weekly basis and Kareena supports Rachelle by being inflexible and unwilling to meet as well.
Task performance refers to behaviour under an individual’s control and how much it supports an organization’s objectives. As a leader, Jovianna’s main focus is to ensure the effectiveness of the group. She grows to be unreceptive of suggestions and criticisms and takes comments about the leadership and disfunction within the SAC personally. As the team’s web designer, Miguel’s lack of attendance and communication hurts the morale of the team. In an e-mail to Jovianna, Tate states her growing lack of motivation due to Miguel’s behavior.
Joining and staying refers to turnover rate in an organization or team and whether its members are compelled to stay. Rachelle and Kareena’s dissatisfaction with the SAC have caused them to deliver an ultimatum: either Jovianna steps down as leader or they leave and take FCC Foundations with them. Despite her earlier enthusiasm, Jovianna mentions that she was about to hand in her resignation due to the conflict within the group.
The MARS Model of Individual Behaviour is split into four categories. MARS is an acronym for motivation, ability, role perception, and situational factors. These are the four factors which influence an individual’s performance and behaviour in the workplace.
Motivation is the internal drive to complete tasks and succeed in the workplace and can be measured by the direction, intensity, and persistence of an individual’s voluntary behaviour. Motivation changes over time and managing motivation is vital to an organization’s success because the combination of direction, intensity, and persistence are the emotional forces which moves an individual into action. 
The members of SAC exhibit different levels of motivation over the course of the case study. Since the founding of the SAC, Miguel was not putting his best effort, as a personal situation interfered with his ability to produce his best work. Examples of lack of motivation include tardiness and unexcused absences. Tate is dedicated to making the alliance work, but she is losing motivation due to Miguel’s lack of commitment as outlined in her e-mail to Jovianna. 
Rachelle and Kareena both suffer from low motivation as they disapprove of Jovianna’s leadership style. They feel that Jovianna is a poor leader and in their private meeting with her they state that “[they] are not motivated to do anything” and tell Jovianna that she is leading the team incorrectly. Based on the fax sent to Jerome, Rachelle and Kareena feel the weekly meetings discourage open and honest dialogue, lack organization, and are altogether unproductive. The combination of Jovianna’s leadership, lack of organization, and Miguel’s continual weak commitment has led them to feel that the SAC will not be able to function without change.
Jovianna’s level of motivation changes over the course of her involvement with the SAC. She was motivated to do well for several reasons. The SAC gave Jovianna a chance for personal growth through developing her leadership and marketing skills, while a successful alliance between Jaztec and FCC Foundations would be beneficial in advancing her career. Jovianna also wanted to prove herself to Jerome and show her capabilities. However, as conflict grew within the group, Jovianna’s motivation decreased. Rachelle and Kareena constantly disrupted meetings with aggressive questions, criticisms, and an open display of resistance towards Jovianna’s leadership. Due to the hostile atmosphere during readings and the lack of results from Miguel, Jovianna’s intensity – the amount of effort allocated to the success of the SAC – decreased significantly and culminated in her lashing out verbally at Rachelle and Kareena during a private meeting instead of attempting to work things out diplomatically. With things spiraling out of control, Jovianna rants to her assistant Amelia and states that she feels like resigning.
Ability is used to describe an employee’s learned capabilities and natural aptitude with relation to any task they are assigned with in the workplace. Aptitudes are natural talents that can be classified as either physical or mental, and an individual’s aptitudes allows them to acquire and learn skills for tasks in the workplace. An employee’s ability will make a significant difference to their workplace behaviour and performance.
Miguel is talented and capable of producing great work. He had shown Jovianna brilliant templates of web pages that he had designed, which made him a valuable member of the team despite his seeming lack of contribution and commitment.
Jovianna lacks leadership ability. Over the course of her leadership of the SAC, Jovianna has shown her inflexibility and incapability of taking criticism and suggestions without involving personal feelings. She has a habit of making assumptions without clarifying or communicating. Before the first SAC meeting and without even speaking to any of the members involved in the alliance, Jovianna assumed that all the members were easy-going, agreeable, and had strong feelings of commitment. Jovianna shows complacency when she uses a flexible leadership style with the committee because she had used the same leadership style in the past and it had been successful. She then shows her inflexibility when asked by Rachelle and Kareena to change her leadership style, rather than attempting to understand the reason for the request, she yelled at the FCC members instead. Prior to the meeting with Rachelle and Kareena, Jovianna made assumptions that the meeting would be about Miguel’s performance and prepared herself for that without clarifying what the meeting was for with Rachelle.
Role perception is an estimation for how clearly employees understand their duties within a team or the workplace, and an accurate role perception will allow employees to perform their tasks well. Role perception is graded on a scale from role ambiguity to role clarity. A global survey suggests that employers should target maximum role clarity to have higher workplace productivity. By providing higher role clarity, employees will be motivated because they have confidence that their efforts will result in the desired outcome. In order to increase role clarity employees should understand specific duties and consequences, the priority of tasks and expectations for performance, and understand the preferred behaviour and procedures to completing tasks. If employees have a good level of role clarity, they can allocate time and resources according to the importance of tasks that they are assigned to.
Jovianna does not seem to understand the type of leader that the team requires. While she attempts a flexible leadership style with a serious and professional tone, Rachelle and Kareena find her to be overbearing and wished for a more relaxed tone during SAC meetings. Rachelle and Kareena feel that Jovianna is doing a poor job of motivating the team and is incapable of taking criticism. Rachelle is entrusted to make all final decisions on behalf of FCC Foundations in order for the alliance to function, but her attitude towards Jovianna make the meetings a difficult environment to work in.
As the appointed lead representative and final decision maker for FCC Foundations, Rachelle should be doing her best to work things out between the two organizations. Instead, she chooses to act in a manner that divides the group and creates a hostile atmosphere during meetings. During the first meeting Rachelle stated FCC was not in the alliance for the advancement of Jaztec despite the two organizations having agreed to work collaboratively on this project. Rachelle fails to recognize that based on the nature of collaboration, any success Jaztec achieves will also benefit FCC Foundations. 
Despite not living up to the committee covenant that he signed, it is likely Miguel thinks that his behaviour is acceptable because he has not been reprimanded or held accountable for his actions.
Situational factors are conditions outside an employee’s control that affect their behaviour and performance. As far as we are aware, the only member of the SAC that is heavily influenced by situational factors is Miguel. These factors led him to openly show a lack of dedication to the team by acting against the committee covenant that he had signed. Miguel was always either late or absent from meetings, and despite having completed templates he had not submitted them to the SAC which meant that the other members feel that Miguel has done and contributed nothing. Miguel eventually had an emergency so urgent that he flew to Spain and did not even notify anyone until he landed. All these counterproductive work behaviours are due to the situational factors from his personal life. 
Researchers measure a team’s effectiveness by the benefits it provides to the organization it serves and whether or not it has the longevity needed to fulfill its purpose. The Team Effectiveness Model combines components from multiple models developed through research focused on identifying features and conditions which make teams more effective.
Organizational and team environment views the environment as an uncontrollable resource that either inhibits or supports a team’s ability to be effective. Its elements overlap with situational factors outlined in the MARS Model, focusing explicitly on conditions or factors which directly influence team effectiveness but are beyond the team’s boundaries and control. Miguel’s personal issue is the uncontrollable factor affecting the SAC and causing him to act against the committee’s covenant. Miguel demoralizes group members by failing to show tangible progress on the website and displaying a visual lack of commitment to attending meetings.
The team design aspect of the Team Effectiveness Model focuses on how a team will be ineffective if team composition, size, roles, or task characteristics are poorly designed. While both companies are almost evenly represented within the SAC, the committee is not the right size because has not reached its ideal size. A team is at its optimal size when members provide all the necessary competencies in order to perform the work. The main competencies based on the Team Member Competency Model is cooperating, coordinating, communicating, comforting, and conflict resolving.
The SAC lacks a conflict resolver. Kareena and Rachelle struggle to cooperate with Jovianna and are unaccommodating to her requests for future meetings. Jovianna shows poor coordination skills as Kareena, Rachelle, and Tate all express feelings that the team is not on track. She also fails to communicate that Miguel has in fact created websites, and her outburst at Rachelle and Kareena shows a lack of respect for the two women’s opinions. Miguel struggles to communicate his problems with the team and does not share his website templates despite having already completed them. Miguel’s preference to work alone and do things on his own terms is not the right attitude for collaborative work.
The SAC lacks clear roles and struggles with low task interdependence, which is the extent that team members must share information, materials, or expertise between each other. The SAC’s only indicator of progress is its website, but the only SAC member with the ability to design the website is Miguel.  A set of well-structured tasks promotes coordination within a team, and an alliance between two organizations is complex work which requires knowledge and expertise beyond any one member. 
Team norm, cohesion, efficacy, and trust are used to describe the constantly changing motivation and cognitive characteristics of a team, and these elements are collectively known as team states. Norms are rules and expectations established by group members, and cohesion is defined as the degree team members wish to continue their association and membership with the team. The SAC struggles most with team norms and cohesion. 
SAC members are expected to comply with the committee covenant, but each member has violated various aspects of the covenant. Jovianna does not value Rachelle and Kareena’s wishes for the meeting be organized and follow an agenda, and when they try to meet with her and give her feedback, she attacks their criticism by speaking disrespectfully. This is a display of a leader who does not encourage or appreciate her team members. 
Rachelle and Kareena ruin the dynamics of the team by being difficult to work with and instead of working with Jovianna’s unique personality and diverse skills, they choose to pick at and magnify her weaknesses as a leader. They are also guilty of bearing hard feelings towards Jovianna by saying things like “we hate this project because of you”, being discussion killers during meetings, and attacking Jovianna with severe negative feedback and overly critical comments. 
Miguel fails to honour the covenant by not providing up to date information regarding the website and does not respect that meetings should start on time. Miguel’s behaviour and inadequate performance should not be tolerated as he openly displays a lack of respect for the covenant. By saying nothing but being disgruntled, Tate – and all other members dissatisfied with Miguel’s performance – is guilty of not executing her right to ask Miguel to resign from the team because he has not been meeting established expectations.
Team processes are described through interaction and dynamics between team members, and how well they perform overall. The Five-Stage model is used to describe the idea of team development and explain a team’s performance based on the stage they are in. As teams develop and mature, they reach different stages which have unique characteristics. These are the five stages of team development:
1.	Forming – is the period where members are discovering expectations and testing boundaries of behaviour.
2.	Storming – is the phased marked by conflict between members and competition for roles. Behaviours and performance standards are established here.
3.	Norming – is reached when the team has achieved cohesion and members have well established roles.
4.	Performing – is when teams are working together at a high level. Members trust each other, identify as part of the team, and are committed to the fulfilling the objectives collaboratively.
5.	Adjourning – happens when the assigned task is complete and the team is about to disband. Members focus on their relationships with other members rather than the task.
Miguel used the forming stage to test the boundaries for tardiness and attendance, continuing to be late or not show up because he was never reprimanded during that stage. Rachelle and Kareena used the forming stage to test the limitations for their negative behaviour towards Jovianna. As the SAC moved past the norming stage, it became stuck the storming stage and members are experiencing various levels of interpersonal conflict.
A team becomes more effective through time and development. When a team fulfills its purpose and completes the task it set out to do, members have their needs satisfied, and the team’s survival is no longer in question, it has reached the highest point of effectiveness. The SAC has a long way to go in order to reach this point. It still struggles with aspects from organization and team environment, team design, team states, and team processes.
In order to reach the ideal team size and increase cooperation through higher task independence, the SAC should add another web developer into the team. The team is not the ideal size because it lacks a conflict resolver and has low task interdependence. The new web developer should have the capacity to act as a conflict resolver when there is tension between SAC members. This greatly benefits the team by improving relationships between Jovianna, Rachelle, and Kareena. In addition, task interdependence will increase by requiring Miguel to work collaboratively with another developer.
Following the addition of a new developer, the SAC should adjust team roles and reassign tasks between members. Everyone should be assigned a specific role, understand the requirements of the role, and deadlines for their assigned tasks. Team members should be given the chance to provide feedback on role clarity and if they have any questions or issues regarding their assigned role. By having clear role perceptions and understanding their duties as members of the SAC, the team members will be able to direct their effort accordingly and focus on the most important tasks first. Role clarity also improves motivation by increasing their belief that their effort will produce a positive outcome. This especially applies to Rachelle and Kareena who feel like the alliance is a failure. By having a clear idea of what each member will contribute, Rachelle and Kareena will have a better understanding of how the team will be successful.
Miguel should disclose the progress of his website with SAC members since he has already produced magnificent templates according to Jovianna. This provides team members a tangible indicator of progress. By seeing the progress of the website, team members are able to contribute to the project by providing information for the web developers to display on the website. By connecting the tasks of each member together, the team is in a state of reciprocal interdependence where members are able to exchange work back and forth which results in increased collaboration. Weekly reports will keep each member accountable and allow other members to quantify their contributions.
Miguel should be reprimanded for his behaviour and Jovianna should immediately notify him via e-mail stating that he must either adhere by the committee covenant or be replaced. There are two possible outcomes from reprimanding Miguel. Miguel can agree to comply with the committee’s covenant and only one additional web developer is required. In this way, the committee is able to ensure that Miguel is held accountable for his actions. Alternatively, if Miguel is uncompliant, he is removed from the team and Jovianna will bring two additional web developers into the project. Through removing Miguel from the project, it shows that efforts are being made to ensure the success of the project. 
The team should look for a mediator to reduce tension between Jovianna and Rachelle and restore a working relationship between the two women. This should be a non-biased individual who can manage the interaction between disputing parties. Jovianna should issue a formal apology to Rachelle and Kareena as part of the mediation process. In return, Rachelle and Kareena should be more respectful of her position as leader of the alliance. 
In response to Rachelle and Kareena’s fax to Jerome, SAC meetings should be more structured. Agendas should be sent 72 hours in advance in order to give members ample time to prepare since requesting agendas one week in advance is unreasonable if meetings are occurring weekly. One team member will be assigned to take minutes during meetings and send it to the team within 8 hours after meetings conclude. The web developer(s) should give progress updates each meeting to quantify the progress of the project. Daily progress reports are unnecessary because the timeframe is not long enough for any significant changes to be made. Reports of Jovianna’s meetings with Jerome should be kept private, and Jaztec should not be obligated to disclose internal meetings with FCC employees.
"""


# document1 = abc_scraper(url='https://abcnews.go.com/International/wireStory/thousands-protest-anniversary-brazils-coup-62077492')
# document1 = guardian_scraper(url='https://www.theguardian.com/environment/2019/mar/29/can-the-world-quench-chinas-bottomless-thirst-for-milk')
# document1 = ctv_scraper(url='https://www.ctvnews.ca/politics/you-might-get-a-text-from-andrew-scheer-telling-you-to-fill-your-gas-tank-1.4355710')
document1 = nbc_scraper('https://www.nbcnews.com/tech/internet/facial-recognition-s-dirty-little-secret-millions-online-photos-scraped-n981921')

nlp = spacy.load("en_core_web_sm")

# build an NLP object
docx = nlp(document1)

# tokenization of text
mytokens = [token.text for token in docx]

# build word frequency
# word.text is tokenization in spacy
word_frequencies = {}
for word in docx:
    if word.text not in stopwords:
        if word.text not in word_frequencies.keys():
            word_frequencies[word.text] = 1
        else:
            word_frequencies[word.text] += 1

# maximum word frequency
max_f = max(word_frequencies.values())

for word in word_frequencies.keys():
    word_frequencies[word] = (word_frequencies[word]/max_f)

# frequency table
# print(word_frequencies)

# sentence tokens
sentence_list = [sentence for sentence in docx.sents]

# sentence score via comparison between words and sentence
sentence_scores = {}
for sent in sentence_list:
        for word in sent:
            if word.text.lower() in word_frequencies.keys():
                if len(sent.text.split(' ')) < 30:
                    if sent not in sentence_scores.keys():
                        sentence_scores[sent] = word_frequencies[word.text.lower()]
                    else:
                        sentence_scores[sent] += word_frequencies[word.text.lower()]

# sentence score table
# print(sentence_scores)

summarized_sentences = nlargest(7, sentence_scores, key=sentence_scores.get)
# print(summarized_sentences)

# convert sentences from spacy span to strings for joining entire sentence
for w in summarized_sentences:
    print(w.text)

# List Comprehension of Sentences Converted From Spacy.span to strings
final_sentences = [w.text for w in summarized_sentences]
summary = ' '.join(final_sentences)
print('\n\n\n\n\n\n\n\n\n', summary)

print('The original document had', len(document1), 'words, the summary has', len(summary), 'words.')
